
modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="customconduit"
version="1.0"
displayName="Custom Conduit Structure"
description="Cambia la forma de activación del canalizador"
